buildscript {
    ext.kotlin_version = '1.9.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // AGP dikelola via plugins{} di settings.gradle (8.1.1).
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://www.jitpack.io"
            credentials { username "jp_0mfc85filda9a7qg0q6g0oef1h" }
        }
    }
    
    plugins.withId('com.android.library') {
        android {
            if (!hasProperty('android.namespace')) {
                namespace = findProperty('GROUP') ?: 'com.example.namespace'
            }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
